# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8ebbc47ea8c2c374c33de5f82db9dcd5678b43dc5f591ea0bf79c230c4d9a6821b81d51163a4b9884b39051fe182a8b244bb0bc20963675186a98f41a969b41

test:
  secret_key_base: 83250ce4eb7fc68134e38ce64ae67cc9991802386f0d1b8ec7759440b532c1c72caf7c6d4cdf54933fbfb505daf232b1a349cb2b552e449d28960aca76bbef2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
